spring.application.name=TheDeckForge
spring.datasource.url=jdbc:mysql://localhost:3306/deckforgeDB
spring.datasource.username=root
spring.datasource.password=Fucking8008Password
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver
spring.security.user.password=root
spring.security.user.name=root

spring.sql.init.mode=always
spring.sql.init.separator=;

spring.thymeleaf.cache=false

server.port=8080